app:
  batch:
    work-dir: C:\\Users\\jkanm\\Downloads\\title.basics.tsv
    chunk-size: 50000
    thread:
      max-pool-size: 20
      core-pool-size: 15
  api:
    movie:
      limit: 60
logging:
  level:
    root: info
    com:
      kleematik: debug
    org:
      springframework:
        web: info

spring:
  datasource:
    url: jdbc:h2:file:F:/999-Sandbox/imdb/h2/data
    driver-class-name: org.h2.Driver
    name: imdb
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false