app:
  batch:
    chunk-size: 50000
  api:
    movie:
      limit: 60
logging:
  level:
    root: warn
    com:
      kleematik: warn
    org:
      springframework:
        web: warn

spring:
  application:
    name: imdb
  datasource:
    driver-class-name: org.postgresql.Driver
    name: imdb
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
      temp:
        use_jdbc_metadata_defaults: false
  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false